### ISSUE TITLE
Pitches: Share your CivicCamp session idea before the conference

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#1194]
If you plan on pitching an unconference session this year for CivicCamp, please add a comment to this issue with the proposed title and your name. Feel free to add a brief description. We will list the submitted proposals to the website schedule page so attendees can start to formulate a few topics that will be at the unconference.

Disclaimer: you must be present at CivicCamp on Friday, September 29 to make your pitch in person at approximately 11:35 am at the Red Hat Annex.

**Comment by jhibbets** [comment]
Discussion topic: What are the challenges to using open data?

**Comment by ChrisTheDBA** [comment]
Wake County is launching a new transparency portal. Please tell us what we did wrong. Need video.

**Comment by ChrisTheDBA** [comment]
Code for San Francisco started a Data Science Working Group. We could totally do that too! https://codeforsanfrancisco.org/projects/the-data-science-working-group/

**Comment by LauraMB12** [comment]
How can we create a better way to connect people with resources / services? Maybe a more human/user-centered approach, instead of lists/directories of resources. (e.g. 211, Durham Network of Care [http://durham.nc.networkofcare.org/mh/(url) )
Multiple aspects to consider:
- How to create something that's easy for residents to use
- How to create something that minimizes the effort needed to keep it up to date 
- How to create something that helps us understand how people are connecting with resources / services (data, trends, etc.)

**Comment by LauraMB12** [comment]
How can civic tech help during emergency situations? (e.g. hurricanes)
What problems are not being addressed by other organizations? How can we fill these gaps?

**Comment by LauraMB12** [comment]
How can civic tech help schools? 
(We do a lot with cities and counties, but not school systems.)

**Comment by LauraMB12** [comment]
How can we tell if our projects make a difference? How do we measure / monitor / evaluate success / impact?

**Comment by LauraMB12** [comment]
How can we increase the diversity of people involved in our projects / events?
(age, gender, race, ethnicity, education level, disability, technical experience, location, etc.)

**Comment by jhibbets** [comment]
Final: http://ncopenpass.com/blog/unconference-grid-2018/
