### ISSUE TITLE
Need to pull together social media list for  Civic Camp speakers/judges

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1209]
Previous year's the social meida list was on the detailed schedule page

**Comment by jtawes** [comment]
was citycampnc.org taken down?

**Comment by jhibbets** [comment]
No, looks like a server error. @christhedba - that's on your AWS??

**Comment by jhibbets** [comment]
Nope, its on Just Host

**Comment by ChrisTheDBA** [comment]
I don't know anything about it. It's still running on my AWS...for now. :)
Chris Mathews

**Comment by jtawes** [comment]
I've created a small spreadsheet because I had to try and look up a lot of missing information on all of the speakers. I wasn't able to find twitter accounts for everyone but was able to find linkedin accounts for everyone except Alvarez.  How would you like this presented? Should I only show those speakers with twitter handles? Should I include linkedin info for everyone or just use linkedin for those without twitter? Should I include email if we have it? If anyone has additional information to add, please feel free. I can add the widget as soon as I know what you would like to include. I will also update the same contact info for everyone on the speakers page.
[socialmedialinks.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6b412c71616500119ddf73/125516c66e82c728ace21e0d46fb9b992a838fa48aedb642a854fe9f3a046b313916ac217586f76ae5002e570b0a4dad41595c41f8f9882cf2e33c72db0d02ead83b4d68d47f40f2ecdd42e64bef62994597b7b4804dc5eb3a24e78e8f493f1800119bb2.xlsx)

**Comment by jtawes** [comment]
I moved it to the Marketing Folder, here is the spreadsheet:
https://drive.google.com/open?id=1YWffu3bSHkhJG-0MzSKkKHA1hzNcrvkn

**Comment by jhibbets** [comment]
I created a speaker contact list the other day, I hope it wasn't too much
effort for the work you did:
https://docs.google.com/spreadsheets/d/11CXgAQJA-dM62G0WrxmCvvTIhX9FacUDZ5aD4ZzthN8/edit#gid=0

I would show the social media accounts that we have and if they don't have
Twitter for example, then don't show the icon. I would not share their
email.

Jason

**Comment by jtawes** [comment]
We don't have any social media for Alvarez, do I just leave him off of the guide? Also, I have a found some twitter handles that aren't on your list, I replaced the twitter handles you had with some of the ones I found. Should I include the twitter handles I found for the people you don't have ones for?

**Comment by jcwlib** [comment]
I would just use the City of Fayetteville for Alvarez - that's what I did for the social media tweets about the keynotes.  If we are able to find social media handles for presenters - I would include them.

**Comment by jhibbets** [comment]
Thanks!
