### ISSUE TITLE
Build electronic unconference board

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1236]
based on last year's blog post-http://ncopenpass.com/blog/friday-september-23-unconference-schedule-the-grid/

**Comment by jcwlib** [comment]
@jhibbets to provide more details (if needed)

**Comment by jhibbets** [comment]
@jtawes Let me know if you have any questions. 

- [ ] Sessions times are: 1pm, 2pm, 3pm, 4pm.
- [ ] Room names: Pender/Dodgeball (80), New Hanover/Red Rover (25), Brunswick (15), Carteret (15)

**Comment by jhibbets** [comment]
Oh, and we talked about opening the pantry at 3pm so we can have a 5th column with Taco bar at 1pm and 2pm, then add room name Onslow (15)

**Comment by jtawes** [comment]
I created a draft post titled "Unconference Grid - 2018". I created the
empty table with the conference rooms as headers. I also set up the post to
show a different version on mobile since the table would be cut off at that
size, so you will see the table on Desktop and Tablet but on mobile it
converts to sections by time.

**Comment by jhibbets** [comment]
@jtawes looks great, thanks for helping me get it set-up
