### ISSUE TITLE
Send personal Thank you's to speakers, judges, and trainers

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1270]

**Comment by jhibbets** [comment]
Include a discount code to DataPalooza

**Comment by jhibbets** [comment]
@jcwlib - can I get a second set of eyes on this before I send out?

https://docs.google.com/document/d/1y1uWFZy1JKvKi61JrM5Xl2QA3yK5w45oC8L4NcsVvmQ/edit

TIA

**Comment by ChrisTheDBA** [comment]
I think that 150 is quite a stretch and even deceitful. We printed 118 name
badges and have over 40 that were never picked up. Adding in the people
that weren't on the list, it's maybe 80 people total in attendance.

No one who was there would think that we have 150 people.

Paula had an interesting comment. Maybe when we had 200+ people that was
not reflective of our core group. Most people came out of curiosity. The
curiosity period is over.

Chris Mathews

**Comment by jhibbets** [comment]
I was tallying the number from each individual event, that' how I got
there. Let me know what we feel comfortable with. I do not want to mislead
people, but at the same time, want to have decent numbers to share.

**Comment by ChrisTheDBA** [comment]
Like I said we issued about 80 badges to people, If we want to count
someone 3 times because they were there Friday morning, Friday evening and
Saturday then I have to say that is quite trumpish.

if small is our new normal then we just need to adjust our expectations. I
read something that Seth Godin wrote. I also plan on checking out some of
what Adrian Segar has wrote. (https://www.conferencesthatwork.com/)

Next year will be tough getting sponsors who look at numbers. I get that,
we need to be prepared to discuss the value the niche that we occupy.

Chris Mathews

**Comment by jhibbets** [comment]
80 it is.
Big numbers have always been nice, but there is something about quality and
outcomes that overcome that.

OK to send? Anyone else have feedback?

**Comment by jcwlib** [comment]
Reviewed and minor edits were made.  Ready to send.

For the record we had 82 unique people based on our paper registration
"marks" with the following breakdown per "section" of the event:
Friday - 63
Friday evening - 50
Saturday - 32

I know I didn't get every single person that walked in the door on Friday
evening so that number is an estimate.

**Comment by jhibbets** [comment]
Thank you all, I'll send these out shortly.

FYI @zachambrose I'll connect to judges and CC you.

**Comment by jhibbets** [comment]
Be sure to include #1285 in messaging.
