### ISSUE TITLE
Speaker package (template and FAQ)

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#144]

**Comment by jhibbets** [comment]
> ```
> On Tue, Sep 13, 2016 at 11:24 PM, Jason Hibbets <jhibbets@gmail.com

**Comment by jhibbets** [comment]
Hello speakers,

We just got this information from the venue about your presentations.
Please be sure to read through this as you prepare any slides for
presentations.

Remember slides can be emailed to me or Dropbox:
https://www.dropbox.com/sh/4udqiwiqgg2jniv/AAAlW7tDF5GffAUEbmaLJpVNa?dl=0

Thanks,
Jason

_PowerPoint/ProPresenter Guidelines_
● Format: Widescreen. Your slides will default to being 4:3 (standard
screen),
which will not appropriately fit our monitors. They will look best in
widescreen and
give you more space to layout. It should be found under "Format" or
"Layout" in
PowerPoint.
● Fonts: title, 44 minimum. body, 28 minimum for audience readability.
● Fonts: if you have downloaded a special font outside of the standard
built-in fonts
to PowerPoint, please change your font or send us a link to a place where we
can download the font kit. Otherwise your slide will automatically
change to a
standard font and look jumbled in our systems.
● Videos: Embeded videos are hit or miss. We recommend that you send us a
video file or send the link to the YouTube page so that we can download
the file
to play it through ProPresenter on our systems.
