### ISSUE TITLE
Related content on WordPress

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#270]
I was just reading this (Great post Lenae) and noticed the related links at the bottom were all from 2011, any ideas on how to fix this?

http://citycampnc.org/2016/09/14/the-path-to-citycamp-nc-beyond/

**Comment by lenaecb** [comment]
I believe anything tagged with similar tags will get pulled in as 'reference blogs' because of their categorization. I don't think suggested blog posts are pulled in based on posting time, just keyword similarity

**Comment by ChrisTheDBA** [comment]
pretty accurate, actually 100%. all the posts use the same tag and thus will
randomly post as related.
Chris Mathews

On Mon, Sep 19, 2016 6:40 AM, lenaecb notifications@github.com
wrote:
I believe anything tagged with similar tags will get pulled in as 'reference
blogs' because of their categorization. I don't think suggested blog posts are
pulled in based on posting time, just keyword similarity
