### ISSUE TITLE
Help with testing links

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#314]
I need help with testing the links on these two pages:
http://citycampnc.org/speakers/
http://citycampnc.org/schedule/

can someone run them through a validator and make sure the URLs are good? I build all the twitter links by hand because it was faster.

**Comment by ChrisTheDBA** [comment]
Looks good to me
Chris Mathews

On Wed, Sep 21, 2016 12:44 AM, Jason Hibbets notifications@github.com
wrote:
I need help with testing the links on these two pages:
http://citycampnc.org/speakers/
http://citycampnc.org/schedule/

can someone run them through a validator and make sure the URLs are good? I
build all the twitter links by hand because it was faster.

**Comment by marshallj** [comment]
Me too. 

Jason Marshall
