### ISSUE TITLE
Reminder about debrief meeting

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#345]

**Comment by TaxLadyTracy** [comment]
Make sure we try our best to work around Jason Marshall coming from
Greensboro,  we can pick him up from the train station if it works out.
World of Beer North Hills is an excellent place to have it :)

On Sep 25, 2016 9:48 PM, "Jason Hibbets" notifications@github.com wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/codeforraleigh/CityCampNC/issues/345, or mute the
thread

**Comment by suzanneccnc** [comment]
Is there a debrief meeting this evening?

**Comment by jhibbets** [comment]
Yes. The debrief is separate from the celebration that we need to plan.

**Comment by TaxLadyTracy** [comment]
Ok cool....didn't read the whole thing the first time.
