### ISSUE TITLE
T-shirts for CityCamp - decide August 7

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#468]
We should stick with current vendor. Local, good price and service

**Comment by ChrisTheDBA** [comment]
Decide colors

**Comment by ChrisTheDBA** [comment]
Consolidating other thread. I think white logo...colors are in doc file.

https://docs.google.com/document/d/15ehRXAPlRkVt5-46Wg9-xdpY-1egfY01l1fV8EB555Y/edit

**Comment by jhibbets** [comment]
I like both colors. I'm thinking we do the combo logo this year with NC
Open Pass, CityCamp, Datapalooza. That shouldn't be too busy? Maybe @carsi
could do a t-shirt mock-up?

**Comment by ChrisTheDBA** [comment]
I was looking and it does seem kind of confusing on the front of a t-shirt. I would say either CCNC or NC OpenPass with the events on back? That will drive up the price though. Also do we order them for DataPalooza? if so, how many?

**Comment by jhibbets** [comment]
My initial thought was that if we use the same logo as the flag, we would
have t-shirts for both events. Maybe we ask Carsi to do a plain, "NC Open"
with the hexagon logo for the t-shirts. I'll think more about it.

**Comment by ChrisTheDBA** [comment]
I remember us settling on keeping branding separate since it would be
confusing. That being said I think an "OpenPass" shirt is good but the
stacked logos is not good. I would really like New Kind on branding.

Chris Mathews

**Comment by carsi** [comment]
We could have an NC Open Pass shirt sans stacked logo, with the individual
logos on the back of the shirt. This might drive up the price per shirt by
an undetermined amount, but could be a good way to inform attendees what NC
Open Pass is.

We may run into a logistical issue where people may not attend all of the
events/may attend all of the events. We will need to figure out how to
distribute shirts for these individual events since there is no "NC Open
Pass" kickoff event.

Or, we could have separate shirts for each event (CityCampNC will be on
this shirt then, and there will be separate swag for NC Datapalooza and
Civic Spark Day).

**Comment by ChrisTheDBA** [comment]
We only have 10 days until CSD so its unlikely we can get swag printed.

Chris Mathews

**Comment by ChrisTheDBA** [comment]
my DW also mentioned we are limited to the colors available at the vendor. we can't just pick any color. mea culpa.

**Comment by jhibbets** [comment]
8/7  - we decided to just go with CityCamp NC logo this year,  no Open Pass or Datapalooza to confuse our branding. This will also keep costs down. Chris will work with the vendor on color options, we'll also have a staff shirt by a different color

**Comment by carsi** [comment]
We can use the same shirt design from last year then, and use the midtone
blue and red orange as starting points for color options. Printing doesn't
take hex code so we can choose similar colors given the options.
