### ISSUE TITLE
Beer choice trip

### ISSUE THREAD

**Issue by aikimark** [ncopenpass/NCOpenPass#472]
I will be happy to set up a trip to the brewery.  Let me know if you're interested.  I will also accept requests and suggestions for beer style/flavor.

**Comment by TaxLadyTracy** [comment]
Just my opinion but we need to keep it simple maybe 2 types.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: aikimark <notifications@github.com> Date: 7/31/17  11:36 AM  (GMT-05:00) To: codeforraleigh/NCOpenPass <NCOpenPass@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [codeforraleigh/NCOpenPass] Beer choice trip (#472) 
I will be happy to set up a trip to the brewery.  Let me know if you're interested.  I will also accept requests and suggestions for beer style/flavor.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codeforraleigh/NCOpenPass","title":"codeforraleigh/NCOpenPass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codeforraleigh/NCOpenPass"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Beer choice trip (#472)"}],"action":{"name":"View Issue","url":"https://github.com/codeforraleigh/NCOpenPass/issues/472"}}}

**Comment by dtraleigh** [comment]
I agree. 1 or 2. No more.

**Comment by ChrisTheDBA** [comment]
I was thinking a Trophy IPA(low IBU), White St Kolsch and maybe a 3rd, but my heart not set on the 3rd

**Comment by dtraleigh** [comment]
I can ask one of the guys at Trophy if they are interested in throwing us
an in-kind keg. Yes?

**Comment by aikimark** [comment]
I was going to use White Rabbit brewery, like I intended to do last year.  They will do all the delivery/setup and even man the taps.
http://whiterabbitbrewery.com/

**Comment by dtraleigh** [comment]
Let us know what they want to donate! ;)

**Comment by aikimark** [comment]
If you want to seek another beer source, please include me in that process.

**Comment by ChrisTheDBA** [comment]
Seems that White Rabbit closed and a new place opened in its place Vicious Fishes

**Comment by suzanneccnc** [comment]
I am so late to this conversation, but gotta throw some love out for White
Street.

**Comment by aikimark** [comment]
I can second the White Street suggestion.   Since White Rabbit has closed, I need to do a search for sources.

**Comment by ChrisTheDBA** [comment]
Duplicate. closing.

**Comment by aikimark** [comment]
Chris got a good offer from Brice's.  In addition to their regular beers, they have some interesting seasonals.  We'll have to negotiate about what seasonals will be available in late September.

We might also see if they have a Summer beer keg they are trying to move at a discount.

**Comment by aikimark** [comment]
For reference:
http://bricesbrewing.com/ourbeer/
