### ISSUE TITLE
Dinner - After party - Friday

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#486]
Choose vendor, menu

**Comment by aikimark** [comment]
ok.  Is this different than the "After Party" already on the schedule?

**Comment by dtraleigh** [comment]
Same.

**Comment by ChrisTheDBA** [comment]
We have looking at caterers. Suggestions.

**Comment by jhibbets** [comment]
Humble Pie or  Irregardless Cafe might have some good options; Maybe
something via Glenwood South since we're are Google Fiber??

**Comment by dtraleigh** [comment]
Tobacco Road is right across the street and they can probably accommodate
since they too have meeting space (holds like 30-40 people) and regularly
cater business meetings and events inside their huge space.

On the topic of wine for this event, Raleigh Wine Shop is right across the
street also. I don't mind asking if they're interested in setting up a
table and pouring some. The Wine Feed, further up Glenwood, has also done
something similar. If not, no big deal. I'll do the ask.

**Comment by ChrisTheDBA** [comment]
Irregardless cafe is $19+/pp, Humble Pie doesn't have a catering menu. Tobacco road seems better but they don't price/pp, they do it by the dozen. so we need to know what they would suggest for 50 people.

**Comment by jhibbets** [comment]
@dtraleigh - also wondering if we can support any of the businesses
impacted by the fire that are close by. +1 on Tobacco Road

**Comment by ChrisTheDBA** [comment]
I like that angle. +1 

Anyone know someone at Tobacco Road or I can call. I just want to translate their catering menu to "what do we need for 50 people"

**Comment by dtraleigh** [comment]
Nice! I know Little City Brewing has been very vocal about the fact that
the closed streets from the fire are hitting their business.

I know a guy who knows the people behind Tobacco Road, you want me to
inquire?

**Comment by ChrisTheDBA** [comment]
Sounds like we need to talk to these guys.  jalapeno Serrano Ale, I might need to stop by myself. :)

**Comment by dtraleigh** [comment]
Logistics committee meeting at Little City Brewing!

**Comment by dtraleigh** [comment]
Working with Tobacco Road on this one.

**Comment by dtraleigh** [comment]
Booked.
