### ISSUE TITLE
Breakfast -Friday

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#487]
choose vendor, menu

NY Deli past two years

**Comment by ChrisTheDBA** [comment]
looking going with last years NY Deli out of Cary. They were quite popular. Let's think of backups though.

**Comment by dtraleigh** [comment]
What about Yellow Dog? We used them in 2014. They don't do GF or vegetarian
though.

**Comment by ChrisTheDBA** [comment]
Get a quote since we haven't made a decision. +1

Chris Mathews

**Comment by TaxLadyTracy** [comment]
I was going to get prices in pastries from BJ's and do fruit bowl.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Chris Mathews <notifications@github.com> Date: 8/15/17  8:35 PM  (GMT-05:00) To: codeforraleigh/NCOpenPass <NCOpenPass@noreply.github.com> Cc: TaxLadyTracy <tracy.mathews1125@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [codeforraleigh/NCOpenPass] Breakfast -Friday (#487) 
Get a quote since we haven't made a decision. +1



Chris Mathews







On Tue, Aug 15, 2017 at 8:27 PM, Leo Suarez <notifications@github.com>

wrote:

**Comment by dtraleigh** [comment]
BJ's and fruit bowl it is.
