### ISSUE TITLE
New (larger) SD card for the Mevo

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#565]
I left it running today, doing a local recording (barely any audio as I was out of the house) and with HD (lowest res) the 16Gb card filled up after 3 hours of video.

With a 64 Gb card, I bet we can be comfortable at HD and higher resolutions for a day. A supported card is $27.

Would a 128Gb be too much to ask? For about $50, we would be set at 4K resolution, no need to offload during the event, and very future proof.

Let me know if I'm stretching.

**Comment by aikimark** [comment]
What size(s) of SD cards will it accept?  We might find an SD-USB adapter that will allow us to connect an external hard drive.  Then we're looking at TB-level capacity.

Does it also have a USB port?  I'm asking because I have a couple of 64GB thumb drives.  If there's a USB port, I can loan you the thumb drive for the event.

**Comment by dtraleigh** [comment]
It takes microSD cards and I picked compatible cards off of their website
here:
https://help.getmevo.com/hc/en-us/articles/223431848-What-microSD-Cards-Are-Compatible-With-Mevo-

It has a microUSB port but that'll be used for powering it.

**Comment by dtraleigh** [comment]
64 Gb card ordered.
