### ISSUE TITLE
pick up recycling/compost container from City of Raleigh

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#634]
Containers can be picked up anytime during the week of Sept. 25.

**Comment by dtraleigh** [comment]
Where and at what times?

**Comment by suzanneccnc** [comment]
ClearStream recycling containers can be picked up and returned Monday - Friday from 7 am to 5:00 pm at the Solid Waste Services' Administrative Office located at 630 Beacon Lake Drive.

**Comment by snewt-n** [comment]
We're single stream recycling, yeah?

**Comment by suzanneccnc** [comment]
I believe so. We will have containers for aluminum plus glass mixed
together.

**Comment by suzanneccnc** [comment]
*aluminum plus plastic*

**Comment by suzanneccnc** [comment]
5 recycling lids, 3 compost lids, wire frames, bags, yard signs picked-up. Will bring to CoM Friday am.

**Comment by TaxLadyTracy** [comment]
You should probably bring them Thurs when we are setting up for prime spots.  Just my opinion. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: suzanneccnc <notifications@github.com> Date: 9/27/17  11:56 AM  (GMT-05:00) To: codeforraleigh/NCOpenPass <NCOpenPass@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [codeforraleigh/NCOpenPass] pick up recycling/compost container from City of Raleigh (#634) 
5 recycling lids, 3 compost lids, wire frames, bags, yard signs picked-up. Will bring to CoM Friday am.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codeforraleigh/NCOpenPass","title":"codeforraleigh/NCOpenPass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codeforraleigh/NCOpenPass"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suzanneccnc in #634: 5 recycling lids, 3 compost lids, wire frames, bags, yard signs picked-up. Will bring to CoM Friday am."}],"action":{"name":"View Issue","url":"https://github.com/codeforraleigh/NCOpenPass/issues/634#issuecomment-332568884"}}}
