### ISSUE TITLE
Get wifi details for slides

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#758]
Do we have the SSID and the wifi password yet so that I can include those details on the slide decks?

**Comment by wildca01t** [comment]
Christine Quakenbash at HQ Raleigh Marketing would have this information.  I've asked but no response yet. She helped us at Health 2.0 event last week. The wifi password is painted on the wall next to the bar area. Thanks.

**Comment by wildca01t** [comment]
Here you go:  
It's on the wall by the bar but it's HQ capital and HQ@Capital! Is the password. 

Just as an FYI Christie - HQ Capital's Event Mgr is out for the Bluegrass festival but available for a call or email. Natalie Noel - Marketing Manager will be there, and Ayana our Community Coordinator will as well. 

Space will already be set for 130 when you arrive since Greenville Chamber will be there before you. The only thing we will need is help to reset the space at the end of the event.

**Comment by dtraleigh** [comment]
Thanks!

I assume Tourtech will give us this info on Thursday when things are up and running. Then this card will close.
