### ISSUE TITLE
Group organizer photo

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#787]
Where should find a time when all the organizers are together and get a quick group photo

**Comment by zachambrose** [comment]
+1

On Sep 28, 2017 11:37 AM, "Jason Hibbets" <notifications@github.com> wrote:

Where should find a time when all the organizers are together and get a
quick group photo

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeforraleigh/NCOpenPass/issues/787>, or mute the
thread

**Comment by jhibbets** [comment]
Trying to do this at 2:45 pm today
