### ISSUE TITLE
reimbursement for Compost Now payment

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#891]
payment receipt uploaded to logistics folder. Don't recall how to go about getting reimbursed; if someone could help me with that, I'd appreciate it.

**Comment by suzanneccnc** [comment]
no longer a collaborator so can't add labels/milestones/move to "ready"

**Comment by TaxLadyTracy** [comment]
Expensify is the app to upload


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: suzanneccnc <notifications@github.com> Date: 10/20/17  8:03 PM  (GMT-05:00) To: codeforraleigh/NCOpenPass <NCOpenPass@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [codeforraleigh/NCOpenPass] reimbursement for Compost Now payment (#891) 
payment receipt uploaded to logistics folder. Don't recall how to go about getting reimbursed; if someone could help me with that, I'd appreciate it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codeforraleigh/NCOpenPass","title":"codeforraleigh/NCOpenPass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codeforraleigh/NCOpenPass"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"reimbursement for Compost Now payment (#891)"}],"action":{"name":"View Issue","url":"https://github.com/codeforraleigh/NCOpenPass/issues/891"}}}
